import { Montserrat } from "next/font/google";
import { GlobalContext } from "@/components/GlobalContext";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";

export const metadata = {
  title: "Crypto Currencies",
  description: "Generated by create next app",
};

const montserrat = Montserrat({ subsets: ["latin"] });

export default function RootLayoutClient({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`max-sm:h-dvh ${montserrat.className}`}>
          <GlobalContext>
            <main className="mt-14">
              {children}
            </main>
          </GlobalContext>
        </body>
      </AuthProvider>
    </html>
  );
}
