import { Montserrat } from "next/font/google";
import Navbar from "@/components/Navbar";
import { GlobalContext } from "@/components/GlobalContext";
import "./globals.css";

export const metadata = {
  title: "Crypto Currencies",
  description: "Generated by create next app",
};

const montserrat = Montserrat({ subsets: ["latin"] });

export default function RootLayoutClient({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <GlobalContext>
          <Navbar />
          <main className="mt-14">{children}</main>
        </GlobalContext>
      </body>
    </html>
  );
}
